FROM {{ namespace }}/{{ image_prefix }}prometheus-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% import "macros.j2" as macros with context %}

{% block prometheus_libvirt_exporter_header %}{% endblock %}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
    {% set prometheus_libvirt_exporter_packages = [
        'go',
        'libvirt-devel',
    ] %}
{% elif base_distro in ['debian', 'ubuntu'] %}
    {% set prometheus_libvirt_exporter_packages = [
        'golang-go',
        'libvirt-dev',
    ] %}
{% endif %}

{{ macros.install_packages(prometheus_libvirt_exporter_packages | customizable("packages")) }}

{% block prometheus_libvirt_exporter_version %}
ARG prometheus_libvirt_exporter_version=0.1.1
ARG prometheus_libvirt_exporter_url=https://github.com/kumina/libvirt_exporter.git
{% endblock %}

{% block prometheus_libvirt_exporter_install %}
ENV GOPATH=/build
RUN mkdir /build \
    && cd /build \
    && git clone --branch ${prometheus_libvirt_exporter_version} ${prometheus_libvirt_exporter_url} \
    && cd libvirt_exporter \
    && go get -d ./... \
    && go build \
    && cp libvirt_exporter /opt/ \
    && chmod +x /opt/libvirt_exporter \
    && rm -rf /build
{% endblock %}

{% block prometheus_libvirt_exporter_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER prometheus

