FROM {{ namespace }}/{{ image_prefix }}prometheus-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block prometheus_openstack_exporter_header %}{% endblock %}

{% block prometheus_openstack_exporter_repository_version %}
ENV prometheus_openstack_exporter_version=0.1.0
{% endblock %}

{% block prometheus_openstack_exporter_install %}
RUN git clone https://github.com/stackhpc/openstack-exporter.git /tmp/openstack-exporter \
    && cd /tmp/openstack-exporter \
    && make common-build \
    && cp openstack-exporter /opt/openstack-exporter
{% endblock %}

{% block prometheus_openstack_exporter_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER prometheus
