FROM {{ namespace }}/{{ image_prefix }}prometheus-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block prometheus_openstack_exporter_header %}{% endblock %}

{% block prometheus_openstack_exporter_repository_version %}
ENV prometheus_openstack_exporter_version=0.1.0
{% endblock %}

{% block prometheus_openstack_exporter_install %}
RUN curl -sSL -o /tmp/prometheus_openstack_exporter.tar.gz https://github.com/stackhpc/openstack-exporter/archive/master.tar.gz \
    && tar xvf /tmp/prometheus_openstack_exporter.tar.gz -C /tmp/ \
    && cd /tmp/openstack-exporter-master \
    && make common-build \
    && cp openstack-exporter /opt/openstack-exporter \
    && cd /opt/ \
    && rm -f /tmp/prometheus_openstack_exporter.tar.gz /tmp/openstack-exporter-master
{% endblock %}

{% block prometheus_openstack_exporter_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER prometheus
